require('./deployNormalDistribution')
require('./deployBS')
require('./deployLibs')
require('./deployChainlink')
require('./deployPriceProvider')
require('./deployOracle')
require('./deploySigma')
require('./deployAMMFactory')
